vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - eamodio.gitlens@10.2.1:e0IYyp0efFqVsrZwsIe8CA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - ChakrounAnas.turbo-console-log@1.4.0:wsrgJrbc2BBHH89SOmj8Yg==
    - vscode-icons-team.vscode-icons@10.0.0:9G2nNF/k04qaOhAogmEuMg==
image:
  file: .gitpod.Dockerfile
